# Generated by Django 3.1.1 on 2020-10-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
