# Generated by Django 3.1.1 on 2020-10-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20201018_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='title', max_length=100),
            preserve_default=False,
        ),
    ]
