# Generated by Django 3.1.1 on 2020-10-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20201022_1435'),
        ('recipe', '0007_auto_20201021_1048'),
    ]

    operations = [
    ]
