# Generated by Django 3.1.1 on 2020-10-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20201023_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.TextField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.TextField(max_length=75, null=True),
        ),
    ]
