# Generated by Django 3.1.1 on 2020-10-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_auto_20201023_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
