# Generated by Django 3.1.2 on 2020-10-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_auto_20201023_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
