# Generated by Django 3.1.1 on 2020-10-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_auto_20201029_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Chinese', 'Chinese'), ('BBQ', 'BBQ')], default='test', max_length=20),
            preserve_default=False,
        ),
    ]
