# Generated by Django 3.1.1 on 2020-10-30 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_post_slug'),
        ('recipe', '0016_auto_20201029_0508'),
    ]

    operations = [
    ]
