# Generated by Django 3.1.2 on 2020-10-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_merge_20201030_0443'),
        ('recipe', '0017_merge_20201030_0456'),
    ]

    operations = [
    ]
