# Generated by Django 3.1.2 on 2020-10-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_merge_20201030_1625'),
        ('recipe', '0018_merge_20201030_0507'),
        ('recipe', '0018_auto_20201030_0534'),
    ]

    operations = [
    ]
