# Generated by Django 3.1.2 on 2020-10-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0018_merge_20201030_0514'),
        ('recipe', '0020_remove_post_slug'),
    ]

    operations = [
    ]
