# Generated by Django 3.1.1 on 2020-10-31 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0021_merge_20201030_1043'),
        ('recipe', '0019_merge_20201030_0545'),
    ]

    operations = [
    ]
