# Generated by Django 3.1.2 on 2020-11-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0022_merge_20201031_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
    ]
