# Generated by Django 3.1.2 on 2020-11-05 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0024_auto_20201106_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_img',
            new_name='picture',
        ),
    ]
