# Generated by Django 3.1.2 on 2020-11-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0026_auto_20201106_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('AussieBBQ', 'AussieBBQ'), ('BakedSweets', 'BakedSweets'), ('Bread', 'Bread'), ('Breakfast', 'Breakfast'), ('Burgers', 'Burgers'), ('Chinese', 'Chinese'), ('Dessert', 'Dessert'), ('Drinks', 'Drinks'), ('Fried Food', 'Fried Food'), ('Greek', 'Greek'), ('Indian', 'Indian'), ('Japanese', 'Japanese'), ('Lebanese', 'Lebanese'), ('Mexican', 'Mexican'), ('Pasta', 'Pasta'), ('Pastries', 'Pastries'), ('Pies', 'Pies'), ('Pizza', 'Pizza'), ('Rice', 'Rice'), ('Salad', 'Salad'), ('Sandwich', 'Sandwich'), ('Seafood', 'Seafood'), ('Snacks', 'Snacks'), ('Soup', 'Soup'), ('Steak', 'Steak'), ('Thai', 'Thai'), ('Vegetarian', 'Vegetarian')], max_length=20),
        ),
    ]
